title: Thymeleaf Layout Dialect
description: A dialect for Thymeleaf that lets you build layouts and reusable templates in order to improve code reuse
lang: en-NZ
baseurl: /thymeleaf-layout-dialect
permalink: pretty
theme: just-the-docs
color_scheme: thymeleaf
aux_links:
  "GitHub":
    - https://github.com/ultraq/thymeleaf-layout-dialect
  "GroovyDoc/API":
    - /thymeleaf-layout-dialect/groovydoc/
plugins:
  - jekyll-redirect-from
